//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnosFutbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnosFutbol()
        {
            this.AsistenciaPartidos = new HashSet<AsistenciaPartidos>();
        }
    
        public System.Guid alumno_futbol_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<System.Guid> pago_inscripcion_id { get; set; }
        public Nullable<bool> uniforme_entregado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Pagos Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenciaPartidos> AsistenciaPartidos { get; set; }
    }
}
