//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.AlumnosFutbol = new HashSet<AlumnosFutbol>();
            this.HistorialPlanesPago = new HashSet<HistorialPlanesPago>();
            this.HistorialRepitencias = new HashSet<HistorialRepitencias>();
            this.InscripcionesTalleres = new HashSet<InscripcionesTalleres>();
            this.Pagos = new HashSet<Pagos>();
            this.PersonasAutorizadas = new HashSet<PersonasAutorizadas>();
            this.Tutores = new HashSet<Tutores>();
            this.AlumnosBecas = new HashSet<AlumnosBecas>();
            this.CorteCajaIngresos = new HashSet<CorteCajaIngresos>();
        }
    
        public System.Guid alumno_id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string curp { get; set; }
        public int nivel_id { get; set; }
        public int grado_id { get; set; }
        public string alergias { get; set; }
        public string observaciones { get; set; }
        public string telefono_emergencia { get; set; }
        public string contacto_emergencia { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public System.Guid escuela_id { get; set; }
        public string plan_pagos { get; set; }
        public Nullable<int> mes_sin_pago { get; set; }
    
        public virtual Grados Grados { get; set; }
        public virtual NivelesEducativos NivelesEducativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnosFutbol> AlumnosFutbol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPlanesPago> HistorialPlanesPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialRepitencias> HistorialRepitencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionesTalleres> InscripcionesTalleres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonasAutorizadas> PersonasAutorizadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutores> Tutores { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnosBecas> AlumnosBecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorteCajaIngresos> CorteCajaIngresos { get; set; }
    }
}
