//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnosBecas
    {
        public System.Guid alumno_beca_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public System.Guid beca_id { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public decimal porcentaje_aplicado { get; set; }
        public string observaciones { get; set; }
        public bool activo { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Becas Becas { get; set; }
    }
}
