//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaPartidos
    {
        public System.Guid asistencia_id { get; set; }
        public System.Guid alumno_futbol_id { get; set; }
        public System.Guid partido_id { get; set; }
        public Nullable<bool> asistio { get; set; }
        public Nullable<System.Guid> pago_arbitraje_id { get; set; }
    
        public virtual AlumnosFutbol AlumnosFutbol { get; set; }
        public virtual Pagos Pagos { get; set; }
        public virtual PartidosFutbol PartidosFutbol { get; set; }
    }
}
