//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Becas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Becas()
        {
            this.AlumnosBecas = new HashSet<AlumnosBecas>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public System.Guid beca_id { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public decimal porcentaje { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.Guid> escuela_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnosBecas> AlumnosBecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Escuelas Escuelas { get; set; }
    }
}
