//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConceptosPago()
        {
            this.EscuelaConceptosPago = new HashSet<EscuelaConceptosPago>();
            this.Pagos = new HashSet<Pagos>();
            this.CorteCajaIngresos = new HashSet<CorteCajaIngresos>();
        }
    
        public System.Guid concepto_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public decimal monto_base { get; set; }
        public Nullable<bool> aplica_descuento { get; set; }
        public Nullable<bool> aplica_beca { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.Guid> escuela_id { get; set; }
        public Nullable<decimal> monto_11_meses { get; set; }
        public Nullable<decimal> monto_12_meses { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscuelaConceptosPago> EscuelaConceptosPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorteCajaIngresos> CorteCajaIngresos { get; set; }
    }
}
