//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteCajaIngresos
    {
        public System.Guid detalle_id { get; set; }
        public System.Guid corte_id { get; set; }
        public System.Guid pago_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public System.Guid concepto_id { get; set; }
        public string alumno_nombre { get; set; }
        public string concepto_nombre { get; set; }
        public decimal monto_original { get; set; }
        public decimal descuento { get; set; }
        public decimal recargo { get; set; }
        public decimal monto_pagado { get; set; }
        public string metodo_pago { get; set; }
        public string periodo { get; set; }
        public string referencia { get; set; }
        public System.DateTime fecha_pago { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual ConceptosPago ConceptosPago { get; set; }
        public virtual CortesCaja CortesCaja { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
