//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteCajaGastos
    {
        public System.Guid detalle_id { get; set; }
        public System.Guid corte_id { get; set; }
        public System.Guid gasto_id { get; set; }
        public string concepto { get; set; }
        public decimal monto { get; set; }
        public string tipo_gasto { get; set; }
        public string justificacion { get; set; }
        public bool es_gasto_general { get; set; }
        public System.DateTime fecha_gasto { get; set; }
        public string usuario_registro { get; set; }
    
        public virtual CortesCaja CortesCaja { get; set; }
        public virtual Gastos Gastos { get; set; }
    }
}
