//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CortesCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CortesCaja()
        {
            this.CorteCajaGastos = new HashSet<CorteCajaGastos>();
            this.CorteCajaIngresos = new HashSet<CorteCajaIngresos>();
        }
    
        public System.Guid corte_id { get; set; }
        public System.Guid escuela_id { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public System.Guid usuario_id { get; set; }
        public decimal total_ingresos { get; set; }
        public decimal total_gastos { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal saldo_final { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorteCajaGastos> CorteCajaGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorteCajaIngresos> CorteCajaIngresos { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
