//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscuelaConceptosPago
    {
        public System.Guid escuela_id { get; set; }
        public System.Guid concepto_id { get; set; }
        public decimal monto_base { get; set; }
    
        public virtual ConceptosPago ConceptosPago { get; set; }
        public virtual Escuelas Escuelas { get; set; }
    }
}
