//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenciaGasto
    {
        public System.Guid IdEvidencia { get; set; }
        public System.Guid IdGasto { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public int Tamanio { get; set; }
        public string TipoArchivo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string UsuarioCarga { get; set; }
    
        public virtual Gastos Gastos { get; set; }
    }
}
