//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gastos()
        {
            this.CorteCajaGastos = new HashSet<CorteCajaGastos>();
            this.EvidenciaGasto = new HashSet<EvidenciaGasto>();
        }
    
        public System.Guid IdGasto { get; set; }
        public Nullable<System.Guid> IdEscuela { get; set; }
        public int IdTipoGasto { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public string Justificacion { get; set; }
        public bool EsGastoGeneral { get; set; }
        public Nullable<System.DateTime> FechaGasto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorteCajaGastos> CorteCajaGastos { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvidenciaGasto> EvidenciaGasto { get; set; }
    }
}
