//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialRepitencias
    {
        public System.Guid repitencia_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public string ciclo_escolar { get; set; }
        public string grado_repetido { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string observaciones { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
