//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosNoRegistrados
    {
        public System.Guid pago_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public System.Guid concepto_id { get; set; }
        public decimal monto { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> recargo { get; set; }
        public Nullable<System.Guid> beca_id { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public System.DateTime fecha_aplicacion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string periodo { get; set; }
        public string metodo_pago { get; set; }
        public string referencia { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.Guid> escuela_id { get; set; }
        public string ciclo_escolar { get; set; }
        public Nullable<decimal> monto_pagado { get; set; }
    }
}
