//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionesTalleres
    {
        public System.Guid inscripcion_id { get; set; }
        public System.Guid taller_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<System.Guid> pago_id { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Pagos Pagos { get; set; }
        public virtual Talleres Talleres { get; set; }
    }
}
