//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartidosFutbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartidosFutbol()
        {
            this.AsistenciaPartidos = new HashSet<AsistenciaPartidos>();
        }
    
        public System.Guid partido_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public decimal costo_arbitraje { get; set; }
        public Nullable<bool> realizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenciaPartidos> AsistenciaPartidos { get; set; }
    }
}
