//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasAutorizadas
    {
        public System.Guid persona_id { get; set; }
        public System.Guid alumno_id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string parentesco { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
