//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenDiario
    {
        public System.Guid resumen_id { get; set; }
        public System.Guid escuela_id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total_ingresos { get; set; }
        public decimal total_gastos { get; set; }
        public decimal saldo_neto { get; set; }
        public decimal ingresos_efectivo { get; set; }
        public decimal ingresos_tarjeta { get; set; }
        public decimal ingresos_transferencia { get; set; }
        public decimal ingresos_cheque { get; set; }
        public decimal ingresos_colegiatura { get; set; }
        public decimal ingresos_inscripcion { get; set; }
        public decimal ingresos_uniformes { get; set; }
        public decimal ingresos_talleres { get; set; }
        public decimal ingresos_otros { get; set; }
        public int numero_pagos { get; set; }
        public int numero_gastos { get; set; }
        public int numero_cortes { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual Escuelas Escuelas { get; set; }
    }
}
