//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Alumnos()
        {
            this.T_BecasAlumno = new HashSet<T_BecasAlumno>();
            this.T_Inscripciones = new HashSet<T_Inscripciones>();
        }
    
        public System.Guid IdAlumno { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CURP { get; set; }
        public Nullable<System.Guid> IdNivel { get; set; }
        public Nullable<int> Grado { get; set; }
        public string Alergias { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> IdEscuela { get; set; }
        public System.Guid IdCicloEscolar { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string UsuarioElimina { get; set; }
    
        public virtual C_CicloEscolar C_CicloEscolar { get; set; }
        public virtual T_NivelesAcademicos T_NivelesAcademicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BecasAlumno> T_BecasAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Inscripciones> T_Inscripciones { get; set; }
        public virtual T_Escuela T_Escuela { get; set; }
    }
}
