//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BecasAlumno
    {
        public System.Guid IdAlumno { get; set; }
        public System.Guid IdBeca { get; set; }
        public System.Guid IdCicloEscolar { get; set; }
    
        public virtual C_CicloEscolar C_CicloEscolar { get; set; }
        public virtual C_TiposBeca C_TiposBeca { get; set; }
        public virtual T_Alumnos T_Alumnos { get; set; }
    }
}
