//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuario
    {
        public System.Guid IdUsuario { get; set; }
        public System.Guid IdRol { get; set; }
        public Nullable<System.Guid> IdEscuela { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string ContraseñaHash { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Cargo { get; set; }
    
        public virtual C_Rol C_Rol { get; set; }
        public virtual T_Escuela T_Escuela { get; set; }
    }
}
