//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uniformes
    {
        public System.Guid uniforme_id { get; set; }
        public string tipo { get; set; }
        public string talla { get; set; }
        public decimal precio { get; set; }
        public string niveles_aplicables { get; set; }
        public Nullable<int> inventario { get; set; }
    }
}
