//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosEscuelas
    {
        public System.Guid usuario_escuela_id { get; set; }
        public System.Guid usuario_id { get; set; }
        public System.Guid escuela_id { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
    
        public virtual Escuelas Escuelas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
