//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CorteCaja
    {
        public System.Guid corte_id { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public System.Guid usuario_id { get; set; }
        public decimal total_ingresos { get; set; }
        public decimal total_gastos { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal saldo_final { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public string EscuelaNombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string director { get; set; }
        public Nullable<bool> activo { get; set; }
        public string username { get; set; }
        public string NombreUsuario { get; set; }
        public string email { get; set; }
    }
}
