//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAlumnos
    {
        public System.Guid alumno_id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string curp { get; set; }
        public int nivel_id { get; set; }
        public string Nivel { get; set; }
        public string Grado { get; set; }
        public string GradoNivel { get; set; }
        public int grado_id { get; set; }
        public string alergias { get; set; }
        public string observaciones { get; set; }
        public string telefono_emergencia { get; set; }
        public string contacto_emergencia { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public System.Guid escuela_id { get; set; }
    }
}
