//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPagosConRecargos
    {
        public System.Guid pago_id { get; set; }
        public string alumno { get; set; }
        public string nivel { get; set; }
        public string grado { get; set; }
        public string concepto { get; set; }
        public decimal monto { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> recargo { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<int> dias_atraso { get; set; }
        public string estado { get; set; }
    }
}
