//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaEstadoCuenta
    {
        public System.Guid alumno_id { get; set; }
        public string alumno { get; set; }
        public string nivel { get; set; }
        public string grado { get; set; }
        public Nullable<decimal> total_pagado { get; set; }
        public Nullable<decimal> total_pendiente { get; set; }
        public Nullable<System.DateTime> ultimo_vencimiento { get; set; }
    }
}
