//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AlumnosBecasActivas
    {
        public System.Guid alumno_id { get; set; }
        public string alumno { get; set; }
        public string beca { get; set; }
        public decimal porcentaje_aplicado { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    }
}
