//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CapitalActual
    {
        public string escuela_nombre { get; set; }
        public decimal efectivo_disponible { get; set; }
        public decimal bancos_disponible { get; set; }
        public decimal total_disponible { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
    }
}
