//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ComparacionPlanesPago
    {
        public System.Guid alumno_id { get; set; }
        public string alumno { get; set; }
        public string nivel { get; set; }
        public string grado { get; set; }
        public string plan_actual { get; set; }
        public Nullable<decimal> total_11_meses { get; set; }
        public Nullable<decimal> total_12_meses { get; set; }
        public Nullable<int> mes_sin_pago { get; set; }
    }
}
