//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DetalleIngresos
    {
        public System.Guid detalle_id { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public string escuela_nombre { get; set; }
        public string alumno_nombre { get; set; }
        public string concepto_nombre { get; set; }
        public decimal monto_original { get; set; }
        public decimal descuento { get; set; }
        public decimal recargo { get; set; }
        public decimal monto_pagado { get; set; }
        public string metodo_pago { get; set; }
        public string periodo { get; set; }
        public string referencia { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string estado_corte { get; set; }
    }
}
