//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ResumenCortes
    {
        public System.Guid corte_id { get; set; }
        public string escuela_nombre { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public string usuario_nombre { get; set; }
        public decimal total_ingresos { get; set; }
        public decimal total_gastos { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal saldo_final { get; set; }
        public decimal diferencia { get; set; }
        public string estado { get; set; }
        public Nullable<int> num_ingresos { get; set; }
        public Nullable<int> num_gastos { get; set; }
    }
}
