//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanderson.backend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SeguimientoCambiosCiclo
    {
        public System.Guid alumno_id { get; set; }
        public string alumno { get; set; }
        public string nivel { get; set; }
        public string grado_anterior { get; set; }
        public string grado_nuevo { get; set; }
        public string ciclo_anterior { get; set; }
        public string ciclo_nuevo { get; set; }
        public string plan_anterior { get; set; }
        public string plan_nuevo { get; set; }
        public string tipo_cambio { get; set; }
    }
}
